[package]
name = "load-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
rlt = "0.2.1"
anyhow = "1"
async-trait = "0.1"
clap = { version = "4.5", features = ["derive"] }
reqwest = "0.12"
tokio = { version = "1.36", features = ["rt-multi-thread"] }
